### PR TITLE
[WIP] Feat/custom region form

### PR DESCRIPTION
**Pull request by ThibautGeriz**
### We a more complex use case on the photo classification, I made the following changes:
- add a custom prop `EditForm` to provide a custom react component
- add the props in the custom RegionLabel: regions & imageSrc

### Questions:
- are you happy with the name EditForm?
- I have added in the state, should I leave it in the props?

### CODE REVIEW

**Comment by seveibar** [comment]
Hey @ThibautGeriz, I like how in this implementation you allow replacing the "RegionLabel" component. tbh I don't love having `EditForm` in the state, I might prefer `RegionEditLabel`. This PR hit at a bad time as I just did extensive refactoring to the components.

I'd like to help refactor this or have someone on the wao.ai team help. I'll respond later with more details.

Thanks so much for the contribution! We'll get this merged :)

**Comment by ThibautGeriz** [comment]
@seveibar I've done the requested updates. Let me know when you have time for a full time code review.

**Comment by seveibar** [comment]
This looks good to me.

**Comment by seveibar** [comment]
So I'm going to merge this but we'll need to do just a bit of testing, then it'll go into the next release.

**Pull request merged**
